# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3373cdc9d08b7f20c3cb09403434f1cc7420dbc052a2c780d0fb5e2b935a29d62735373fdf0b374295a280939c6f5bab15e17d8f9bff0d1cb304572836b2e99

test:
  secret_key_base: bc9b29bfd9e472c120109dd7e30f6464afc095888e60fca035890b288ac2f08b3bebbf7f2756879bb12bbb27b6c5cf6d757a8ae98587899e7d2d7e0e7d1312e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
